import { ArrowLeft, Check, Clock3, MapPin, MountainSnow, Play, Target, TrendingUp, Upload } from 'lucide-react';
import { abilities, instructorNotes, student, visits } from '@/lib/mock-data';
import { calculateSkiLevel, terrainLabel } from '@/lib/skilevel';

export default function InstructorQuickView() {
  const level = calculateSkiLevel(abilities);
  const note = instructorNotes[0];
  return (
    <main className="min-h-screen bg-[#eef3f4] pb-12 text-[#102a2e]">
      <header className="sticky top-0 z-10 border-b border-white/10 bg-[#123c43] text-white"><div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4"><a href="/" className="grid size-11 place-items-center rounded-full bg-white/10" aria-label="Back"><ArrowLeft className="size-5" /></a><span className="flex items-center gap-2 font-extrabold"><MountainSnow className="size-5 text-[#d9f26e]" /> Instructor quick view</span><span className="w-11" /></div></header>
      <div className="mx-auto max-w-4xl space-y-4 px-4 pt-5">
        <section className="overflow-hidden rounded-3xl bg-[#123c43] p-6 text-white sm:p-8"><div className="flex items-center gap-4"><div className="grid size-16 place-items-center rounded-2xl bg-[#d9f26e] text-xl font-black text-[#123c43]">{student.initials}</div><div><p className="text-sm font-semibold text-[#d9f26e]">{student.sport} · {student.age} years old</p><h1 className="text-3xl font-black tracking-tight">{student.name}</h1><p className="mt-1 flex items-center gap-1.5 text-sm text-white/65"><MapPin className="size-4" /> Home: {student.homeMountain}</p></div></div><div className="mt-6 grid grid-cols-[auto_1fr] items-center gap-5 rounded-2xl bg-white/10 p-4"><div className="grid size-20 place-items-center rounded-full border-[7px] border-[#d9f26e]"><div className="text-center"><strong className="block text-2xl font-black leading-none">{level}</strong><span className="text-[10px] font-bold text-white/60">OF 5</span></div></div><div><p className="font-black">Blue skier moving into blacks</p><p className="mt-1 text-sm leading-5 text-white/65">Strong fundamentals. Best next terrain: groomed, lower-angle black runs.</p></div></div></section>
        <section className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-6"><div className="mb-5 flex items-center gap-2"><TrendingUp className="size-5 text-teal-700" /><h2 className="text-lg font-black">Terrain at a glance</h2></div><div className="grid gap-x-8 gap-y-4 sm:grid-cols-2">{abilities.map((item) => <div key={item.terrain}><div className="mb-1.5 flex justify-between text-sm"><span className="font-semibold">{terrainLabel(item.terrain)}</span><strong>{item.rating}/5</strong></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-700" style={{ width: `${item.rating * 20}%` }} /></div></div>)}</div></section>
        <div className="grid gap-4 sm:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 text-lg font-black"><MountainSnow className="size-5" /> Mountain history</h2><div className="mt-4 space-y-4">{visits.map((visit) => <div key={visit.mountain} className="flex items-start justify-between gap-3 border-b border-slate-100 pb-3 last:border-0 last:pb-0"><div><p className="font-bold">{visit.mountain}</p><p className="text-sm text-slate-500">{visit.trail} · {visit.difficulty}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${visit.comfort === 'Challenging' ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'}`}>{visit.comfort}</span></div>)}</div></section><section className="rounded-3xl bg-[#d9f26e] p-5"><h2 className="flex items-center gap-2 text-lg font-black"><Target className="size-5" /> Working on</h2><div className="mt-4 space-y-3">{student.focus.map((item) => <p key={item} className="flex items-center gap-2 font-semibold"><span className="grid size-6 place-items-center rounded-full bg-[#123c43] text-white"><Check className="size-3.5" /></span>{item}</p>)}</div><div className="mt-6 rounded-2xl bg-white/55 p-4"><p className="text-xs font-bold uppercase tracking-wider opacity-60">Suggested terrain</p><p className="mt-1 font-black">{note.suggestedTerrain}</p></div></section></div>
        <section className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-500">Latest instructor note</p><h2 className="text-lg font-black">{note.instructor} · {note.mountain}</h2></div><span className="flex items-center gap-1.5 text-sm text-slate-500"><Clock3 className="size-4" /> {note.date}</span></div><div className="mt-5 grid gap-4 text-sm leading-6 sm:grid-cols-3"><div><strong className="block">Observed</strong><p className="text-slate-600">{note.observed}</p></div><div><strong className="block">Practiced</strong><p className="text-slate-600">{note.practiced}</p></div><div><strong className="block">Next step</strong><p className="text-slate-600">{note.nextSteps}</p></div></div><button className="mt-6 min-h-12 w-full rounded-xl bg-[#123c43] font-bold text-white">Add instructor note</button></section>
        <section className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-semibold text-slate-500">Technique video</p><h2 className="text-lg font-black">Recent skiing clips</h2></div><button className="flex min-h-11 items-center gap-2 rounded-xl bg-[#123c43] px-4 text-sm font-bold text-white"><Upload className="size-4" /> Upload</button></div><div className="mt-5 grid min-h-36 place-items-center rounded-2xl bg-[linear-gradient(135deg,#123c43,#2f646a)] text-white"><button className="grid size-14 place-items-center rounded-full bg-[#d9f26e] text-[#123c43]" aria-label="Play recent skiing clip"><Play className="ml-0.5 size-6 fill-current" /></button><span className="sr-only">Stowe carving practice, January 18, 2026</span></div><p className="mt-3 text-sm font-semibold">Stowe carving practice <span className="font-normal text-slate-500">· Jan 18, 2026</span></p></section>
      </div>
    </main>
  );
}
